### ISSUE TITLE
No capitals or special characters options

### ISSUE THREAD

**Issue by kootenpv** [libeclipse/visionary#6]
They are often required.

**Comment by kootenpv** [comment]
We get the strength from using a password with 32+ length; I don't think there is an issue just replacing the first character with ! and using `.title()` on the rest?

**Comment by awnumar** [comment]
I get what you're saying but it feels.. tacky to do it like that. I'm planning a proper deterministic algorithm to run on the scrypt-generated result.

**Comment by otommod** [comment]
All the code for this comment can be found here: https://gist.github.com/otommod/f0f0d4c34b99eba9c7c0193e8b959ab9

Consider the following proposal:  You can treat the key (as given by `pyscrypt.hash`) as a (big) number in base 256.  Encoding the key involves a potential base transformation and a mapping of the values of the digits of the number to characters.

For example, when you do `codecs.encode("hex")` that can be thought as equivalent to the following (function `in_hex` in the gist): 

``` python
n = from_base(hashed, 256)
hex = in_base(n, 16)
encoded = ''.join(string.hexdigits[i] for i in hex)
```

In regards to this issue, there are 100 non control characters in ASCII.  given in `string.printable` in Python.  Encoding the passwords such that it (probably) contains symbols and capitals is (`encode` from gist): `encode(hashed, string.printables)`.

I say probably because they key may not contain any symbol (or capital), same way it may not contain any, say, 5 with the current representation.  As such, this comment may not solve the issue entirely, if a symbol (or capital) is necessitated by some (awful) site or whatnot.

You could even use the same technique to generate passphrases a la https://xkcd.com/936/.

I'm definitely not a security expert so I don't know if there are any bad security implication from all that.

**Comment by awnumar** [comment]
Just to confirm, what's the expected division behavior here:

```
    while x:
        digits.append(x % base)
        x //= base
```

True division or floored?

**Comment by kootenpv** [comment]
I also experimented, and for example using `.title()` there will be situations where there will be no lowercase characters. Kind of stating the obvious, but you will most likely want a deterministic way to generate 1 lower, 1 upper, 1 number, 1 control character _all-the-time_. I also noticed that some control characters are not always allowed; some are more accepted.

It's a tricky situation. I guess we should append a number to the keyword if one way wouldn't work out? Also, what to do when the "facebook" password expired and we have to choose a new one... what is your suggested way? I guess append "1,2,3,4,5 etc", but somehow we have to keep track of that or get into a mess and have to generate 1...n until one of them hits (in case we forgot). Sorry for hijacking this issue with that...

**Comment by awnumar** [comment]
@kootenpv you have a valid point tbh. You're right the security comes from the long password, and a scheme where you convert the hex to decimal and then chr it for ascii may not have symbols and capitals.

Maybe alternating with capitals and lower case is the best thing..

Any ideas on xor'g the hash with the keyword?

**Comment by waynew** [comment]
FWIW, here's the approach that Keepass takes. Of course because it's randomized they can do whatever rules they want.
<img width="475" alt="screenshot 2016-04-29 14 17 20" src="https://cloud.githubusercontent.com/assets/189750/14927065/44f053b2-0e15-11e6-90b1-3a233b7122d7.png">

I know for me personally for this to be useful I would need to have some kind of nth password. A lot of enterprise environments won't let you reuse an password with N months. Obviously I could add the nth myself, but ugh.

One possible approach to adding numbers and casing and symbols would be something like this: https://github.com/fpgaminer/hash-phrase

**Comment by awnumar** [comment]
Ooh I like that human-readable hash thing. I'll add that to my to-do list.
